version: '3'
services:
  cassandra:
    image:  cassandra:4.0.12
    environment:
      - CASSANDRA_CLUSTER_NAME='Cassandra Terraform Provider Test Cluster'
    ports:
      - 9042:9042
    volumes:
      - ./cassandra.yaml:/etc/cassandra/cassandra.yaml